baseurl = "/"
title = "Lost In Superfluous Parentheses"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = '''((Lost In (Superfluous) Parentheses))'''
    description = "The blog of someone who doesn't know Lisp"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

