baseurl = "/"
title = "glitched"
theme = "epictheme"

[author]
name = "The Supreme Leader"

[Params]
    mainSections = ["post"]
    intro = true
    headline = '''glitched.tech'''
    description = "A blog that is, in fact, not about Lisp."
    github = "https://github.com/readabilityLOL"
    email = "techsheep7@proton.me"
    rss = true
    readingTime = true
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[[menu.main]]
name = "blog"
url = "/"
weight = 1

[[menu.main]]
name = "projects"
url = "/project/"
weight = 2

[[menu.main]]
name = "about"
url = "/page/about/"
weight = 4

[[menu.main]]
name = "contact"
url = "/page/contact"
weight = 5
