baseurl = "/"
theme = ["hugo-coder","hugo-github-calendar"]
title = "Glitched"

[author]
name = "The Supreme Leader"

[Params]
    mainSections = ["post"]
    intro = true
    headline = '''glitched.tech'''
    info = "A blog I made."
    github = "https://github.com/readabilityLOL"
    email = "kramningevidence@gmail.com"
    rss = true
    readingTime = true
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    colorScheme = "auto"
    hidecolorschemetoggle = false
    giscus = "readabilitylol/blog"

[Permalinks]
    post = "/:filename/"

[[menu.main]]
name = "blog"
url = "/post/"
weight = 1

[[menu.main]]
name = "projects"
url = "/page/project/"
weight = 2

#[[menu.main]]
#name = "'artwork'"
#url = "/page/stats/"
#weight = 3

[[menu.main]]
name = "about"
url = "/page/about/"
weight = 4

#[[menu.main]]
#name = "contact"
#url = "/page/contact"
#weight = 5

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
