baseURL = "https://glitched.tech"
theme = ["hugo-coder","hugo-github-calendar"]
title = "Glitched"

[author]
name = "Joshua Anand"

[Params]
    mainSections = ["post"]
    intro = true
    headline = '''glitched.tech'''
    info = '''## Welcome to glitched.tech!'''
    github = "https://github.com/readabilityLOL"
    email = "kramningevidence@gmail.com"
    rss = true
    readingTime = true
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    colorScheme = "auto"
    hidecolorschemetoggle = false
    giscus = "readabilitylol/blog"

[Permalinks]
    post = "/:filename/"

[[menu.main]]
name = "blog"
url = "/post/"
weight = 1

[[menu.main]]
name = "notes"
url = "/notes/"
weight = 2

[[menu.main]]
name = "projects"
url = "/page/project/"
weight = 2

[[menu.main]]
name = "now"
url = "/page/now/"
weight = 3


#[[menu.main]]
#name = "contact"
#url = "/page/contact"
#weight = 5
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true


[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[module]
  [[module.mounts]]
    excludeFiles = 'obsidian-notes/*'
    source = 'content'
    target = 'content'
